-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pool2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    out_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_V_full_n : IN STD_LOGIC;
    out_V_write : OUT STD_LOGIC;
    in_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    in_V_empty_n : IN STD_LOGIC;
    in_V_read : OUT STD_LOGIC );
end;


architecture behav of pool2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv8_A9 : STD_LOGIC_VECTOR (7 downto 0) := "10101001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv8_D : STD_LOGIC_VECTOR (7 downto 0) := "00001101";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal out_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal or_cond_reg_572 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal exitcond9_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_1_fu_238_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal k_1_reg_501 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_1_fu_250_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state3 : BOOLEAN;
    signal i_1_fu_273_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_6_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_283_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_reg_525 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal l_1_fu_293_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal l_1_reg_533 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_309_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_reg_538 : STD_LOGIC_VECTOR (7 downto 0);
    signal exitcond8_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_543 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_1_fu_321_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal m_1_fu_341_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal m_1_reg_556 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tmp_5_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_561 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_fu_335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pool_buff_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_reg_576 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal tmp_21_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_reg_590 : STD_LOGIC_VECTOR (0 downto 0);
    signal pool_buff_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal pool_buff_ce0 : STD_LOGIC;
    signal pool_buff_we0 : STD_LOGIC;
    signal k_reg_155 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_4_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_reg_166 : STD_LOGIC_VECTOR (7 downto 0);
    signal exitcond1_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_reg_177 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_reg_189 : STD_LOGIC_VECTOR (3 downto 0);
    signal l_reg_201 : STD_LOGIC_VECTOR (1 downto 0);
    signal m_reg_212 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state10 : BOOLEAN;
    signal tmp_fu_256_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_8_fu_367_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal value_3_fu_479_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_114 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_cast4_fu_279_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_9_fu_299_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_309_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal m_cast2_cast_fu_327_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp4_fu_347_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp4_cast_fu_353_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_17_fu_331_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal array_access_fu_357_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_4_to_int_fu_387_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_to_int_fu_404_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_390_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_fu_400_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal notrhs_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal notlhs_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_407_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_fu_417_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal notrhs6_fu_445_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal notlhs5_fu_439_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_1_fu_473_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_fu_309_p00 : STD_LOGIC_VECTOR (7 downto 0);

    component lenet_hls_fcmp_32ns_32ns_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component pool2_pool_buff IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    pool_buff_U : component pool2_pool_buff
    generic map (
        DataWidth => 32,
        AddressRange => 169,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pool_buff_address0,
        ce0 => pool_buff_ce0,
        we0 => pool_buff_we0,
        d0 => in_V_dout,
        q0 => pool_buff_q0);

    lenet_hls_fcmp_32ns_32ns_1_1_1_U25 : component lenet_hls_fcmp_32ns_32ns_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        din0 => tmp_1_fu_114,
        din1 => value_reg_576,
        opcode => ap_const_lv5_2,
        dout => tmp_21_fu_223_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((exitcond1_fu_232_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_reg_177_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((exitcond9_fu_244_p2 = ap_const_lv1_0) and (in_V_empty_n = ap_const_logic_0))) and (exitcond9_fu_244_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_reg_177 <= ap_const_lv4_0;
            elsif (((tmp_6_fu_267_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i_reg_177 <= i_1_fu_273_p2;
            end if; 
        end if;
    end process;

    j_reg_189_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond8_fu_287_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                j_reg_189 <= j_1_fu_321_p2;
            elsif (((tmp_4_fu_261_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                j_reg_189 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    k_reg_155_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_4_fu_261_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                k_reg_155 <= k_1_reg_501;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                k_reg_155 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    l_reg_201_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_fu_335_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                l_reg_201 <= l_1_reg_533;
            elsif (((tmp_6_fu_267_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                l_reg_201 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    m_reg_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((or_cond_reg_572 = ap_const_lv1_1) and (out_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                m_reg_212 <= m_1_reg_556;
            elsif (((exitcond8_fu_287_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                m_reg_212 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    p_reg_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((exitcond9_fu_244_p2 = ap_const_lv1_0) and (in_V_empty_n = ap_const_logic_0))) and (exitcond9_fu_244_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                p_reg_166 <= p_1_fu_250_p2;
            elsif (((exitcond1_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                p_reg_166 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    tmp_1_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((or_cond_reg_572 = ap_const_lv1_1) and (out_V_full_n = ap_const_logic_0))) and (or_cond_reg_572 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                tmp_1_fu_114 <= value_3_fu_479_p3;
            elsif (((not(((or_cond_reg_572 = ap_const_lv1_1) and (out_V_full_n = ap_const_logic_0))) and (or_cond_reg_572 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10)) or (not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                tmp_1_fu_114 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                k_1_reg_501 <= k_1_fu_238_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                l_1_reg_533 <= l_1_fu_293_p2;
                tmp_15_reg_525 <= tmp_15_fu_283_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                m_1_reg_556 <= m_1_fu_341_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_fu_335_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                or_cond_reg_572 <= or_cond_fu_378_p2;
                tmp_5_reg_561 <= tmp_5_fu_362_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_5_reg_561 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                tmp_21_reg_590 <= tmp_21_fu_223_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond8_fu_287_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                tmp_2_reg_543 <= tmp_2_fu_315_p2;
                tmp_s_reg_538 <= tmp_s_fu_309_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                value_reg_576 <= pool_buff_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, out_V_full_n, in_V_empty_n, ap_CS_fsm_state10, or_cond_reg_572, ap_CS_fsm_state3, exitcond9_fu_244_p2, ap_CS_fsm_state2, ap_CS_fsm_state5, tmp_6_fu_267_p2, ap_CS_fsm_state6, exitcond8_fu_287_p2, ap_CS_fsm_state7, exitcond_fu_335_p2, ap_CS_fsm_state4, tmp_4_fu_261_p2, exitcond1_fu_232_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond1_fu_232_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if ((not(((exitcond9_fu_244_p2 = ap_const_lv1_0) and (in_V_empty_n = ap_const_logic_0))) and (exitcond9_fu_244_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif ((not(((exitcond9_fu_244_p2 = ap_const_lv1_0) and (in_V_empty_n = ap_const_logic_0))) and (exitcond9_fu_244_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((tmp_4_fu_261_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((tmp_6_fu_267_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((exitcond8_fu_287_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (((exitcond_fu_335_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if ((not(((or_cond_reg_572 = ap_const_lv1_1) and (out_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state10_assign_proc : process(out_V_full_n, or_cond_reg_572)
    begin
                ap_block_state10 <= ((or_cond_reg_572 = ap_const_lv1_1) and (out_V_full_n = ap_const_logic_0));
    end process;


    ap_block_state3_assign_proc : process(in_V_empty_n, exitcond9_fu_244_p2)
    begin
                ap_block_state3 <= ((exitcond9_fu_244_p2 = ap_const_lv1_0) and (in_V_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, exitcond1_fu_232_p2)
    begin
        if (((exitcond1_fu_232_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    array_access_fu_357_p2 <= std_logic_vector(unsigned(tmp4_cast_fu_353_p1) + unsigned(tmp_s_reg_538));
    exitcond1_fu_232_p2 <= "1" when (k_reg_155 = ap_const_lv5_10) else "0";
    exitcond8_fu_287_p2 <= "1" when (l_reg_201 = ap_const_lv2_2) else "0";
    exitcond9_fu_244_p2 <= "1" when (p_reg_166 = ap_const_lv8_A9) else "0";
    exitcond_fu_335_p2 <= "1" when (m_reg_212 = ap_const_lv2_2) else "0";
    i_1_fu_273_p2 <= std_logic_vector(unsigned(i_reg_177) + unsigned(ap_const_lv4_2));

    in_V_blk_n_assign_proc : process(in_V_empty_n, ap_CS_fsm_state3, exitcond9_fu_244_p2)
    begin
        if (((exitcond9_fu_244_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            in_V_blk_n <= in_V_empty_n;
        else 
            in_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_V_read_assign_proc : process(in_V_empty_n, ap_CS_fsm_state3, exitcond9_fu_244_p2)
    begin
        if ((not(((exitcond9_fu_244_p2 = ap_const_lv1_0) and (in_V_empty_n = ap_const_logic_0))) and (exitcond9_fu_244_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            in_V_read <= ap_const_logic_1;
        else 
            in_V_read <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond1_fu_232_p2)
    begin
        if (((exitcond1_fu_232_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    j_1_fu_321_p2 <= std_logic_vector(unsigned(j_reg_189) + unsigned(ap_const_lv4_2));
    k_1_fu_238_p2 <= std_logic_vector(unsigned(k_reg_155) + unsigned(ap_const_lv5_1));
    l_1_fu_293_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(l_reg_201));
    l_cast4_fu_279_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_reg_201),4));
    m_1_fu_341_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(m_reg_212));
    m_cast2_cast_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_reg_212),4));
    notlhs5_fu_439_p2 <= "0" when (tmp_16_fu_407_p4 = ap_const_lv8_FF) else "1";
    notlhs_fu_421_p2 <= "0" when (tmp_12_fu_390_p4 = ap_const_lv8_FF) else "1";
    notrhs6_fu_445_p2 <= "1" when (tmp_24_fu_417_p1 = ap_const_lv23_0) else "0";
    notrhs_fu_427_p2 <= "1" when (tmp_23_fu_400_p1 = ap_const_lv23_0) else "0";
    or_cond_fu_378_p2 <= (tmp_2_reg_543 and tmp_13_fu_372_p2);

    out_V_blk_n_assign_proc : process(out_V_full_n, ap_CS_fsm_state10, or_cond_reg_572)
    begin
        if (((or_cond_reg_572 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            out_V_blk_n <= out_V_full_n;
        else 
            out_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_V_din <= 
        value_1_fu_473_p3 when (tmp_5_reg_561(0) = '1') else 
        value_reg_576;

    out_V_write_assign_proc : process(out_V_full_n, ap_CS_fsm_state10, or_cond_reg_572)
    begin
        if ((not(((or_cond_reg_572 = ap_const_lv1_1) and (out_V_full_n = ap_const_logic_0))) and (or_cond_reg_572 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            out_V_write <= ap_const_logic_1;
        else 
            out_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_0_4_to_int_fu_387_p1 <= tmp_1_fu_114;
    p_1_fu_250_p2 <= std_logic_vector(unsigned(p_reg_166) + unsigned(ap_const_lv8_1));

    pool_buff_address0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state7, tmp_fu_256_p1, tmp_8_fu_367_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            pool_buff_address0 <= tmp_8_fu_367_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            pool_buff_address0 <= tmp_fu_256_p1(8 - 1 downto 0);
        else 
            pool_buff_address0 <= "XXXXXXXX";
        end if; 
    end process;


    pool_buff_ce0_assign_proc : process(in_V_empty_n, ap_CS_fsm_state3, exitcond9_fu_244_p2, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (not(((exitcond9_fu_244_p2 = ap_const_lv1_0) and (in_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            pool_buff_ce0 <= ap_const_logic_1;
        else 
            pool_buff_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    pool_buff_we0_assign_proc : process(in_V_empty_n, ap_CS_fsm_state3, exitcond9_fu_244_p2)
    begin
        if ((not(((exitcond9_fu_244_p2 = ap_const_lv1_0) and (in_V_empty_n = ap_const_logic_0))) and (exitcond9_fu_244_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            pool_buff_we0 <= ap_const_logic_1;
        else 
            pool_buff_we0 <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    sel_tmp_fu_468_p2 <= (tmp_5_reg_561 and tmp_22_fu_463_p2);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp4_cast_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_fu_347_p2),8));
    tmp4_fu_347_p2 <= std_logic_vector(unsigned(j_reg_189) + unsigned(m_cast2_cast_fu_327_p1));
    tmp_12_fu_390_p4 <= p_0_4_to_int_fu_387_p1(30 downto 23);
    tmp_13_fu_372_p2 <= "1" when (m_reg_212 = ap_const_lv2_1) else "0";
    tmp_15_fu_283_p1 <= l_reg_201(1 - 1 downto 0);
    tmp_16_fu_407_p4 <= value_to_int_fu_404_p1(30 downto 23);
    tmp_17_fu_331_p1 <= m_reg_212(1 - 1 downto 0);
    tmp_18_fu_433_p2 <= (notrhs_fu_427_p2 or notlhs_fu_421_p2);
    tmp_19_fu_451_p2 <= (notrhs6_fu_445_p2 or notlhs5_fu_439_p2);
    tmp_20_fu_457_p2 <= (tmp_19_fu_451_p2 and tmp_18_fu_433_p2);
    tmp_22_fu_463_p2 <= (tmp_21_reg_590 and tmp_20_fu_457_p2);
    tmp_23_fu_400_p1 <= p_0_4_to_int_fu_387_p1(23 - 1 downto 0);
    tmp_24_fu_417_p1 <= value_to_int_fu_404_p1(23 - 1 downto 0);
    tmp_2_fu_315_p2 <= "1" when (l_reg_201 = ap_const_lv2_1) else "0";
    tmp_4_fu_261_p2 <= "1" when (unsigned(i_reg_177) < unsigned(ap_const_lv4_C)) else "0";
    tmp_5_fu_362_p2 <= (tmp_17_fu_331_p1 or tmp_15_reg_525);
    tmp_6_fu_267_p2 <= "1" when (unsigned(j_reg_189) < unsigned(ap_const_lv4_C)) else "0";
    tmp_8_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(array_access_fu_357_p2),64));
    tmp_9_fu_299_p2 <= std_logic_vector(unsigned(i_reg_177) + unsigned(l_cast4_fu_279_p1));
    tmp_fu_256_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_reg_166),64));
    tmp_s_fu_309_p0 <= tmp_s_fu_309_p00(4 - 1 downto 0);
    tmp_s_fu_309_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_299_p2),8));
    tmp_s_fu_309_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_309_p0) * unsigned(ap_const_lv8_D), 8));
    value_1_fu_473_p3 <= 
        tmp_1_fu_114 when (sel_tmp_fu_468_p2(0) = '1') else 
        value_reg_576;
    value_3_fu_479_p3 <= 
        value_1_fu_473_p3 when (tmp_5_reg_561(0) = '1') else 
        value_reg_576;
    value_to_int_fu_404_p1 <= value_reg_576;
end behav;
