#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun 18 12:12:38 2020

@author: filipe
"""
#this file uses tensorflow 2!

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

import os

from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.models import load_model
from keras.callbacks import CSVLogger

from keras.utils.np_utils import to_categorical


model = load_model('model2.h5')  
# Create a converter
converter = tf.lite.TFLiteConverter.from_keras_model(model)# Convert the model
tflite_model = converter.convert()# Create the tflite model file
tflite_model_name = "model2.tflite"
open(tflite_model_name, "wb").write(tflite_model)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
tflite_quant_model = converter.convert()